insert into drone (DroneID, Manufacturer, Model) values (1, 'SJ', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (2, 'Lumina', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (3, '300ZX', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (4, 'Volare', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (5, '2500', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (6, 'B-Series', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (7, 'Q', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (8, 'F350', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (9, 'S-Series', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (10, 'Integra', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (11, 'SRX', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (12, 'B2600', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (13, 'MKT', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (14, '400E', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (15, 'Highlander', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (16, 'A6', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (17, 'Savana', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (18, 'Escalade EXT', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (19, 'E-Class', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (20, 'RL', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (21, 'M-Class', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (22, 'Landaulet', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (23, 'GT500', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (24, 'V50', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (25, 'Accord', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (26, 'Sable', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (27, 'Freelander', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (28, 'Bronco', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (29, 'Thunderbird', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (30, 'Ram 1500', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (31, 'Frontier', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (32, 'SRX', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (33, 'Sundance', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (34, 'California', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (35, 'Boxster', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (36, 'Fit', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (37, 'Navigator L', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (38, 'Dakota', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (39, 'Discovery', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (40, 'C-Class', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (41, 'rio', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (42, 'Cougar', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (43, 'M3', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (44, 'Cruze', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (45, 'Voyager', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (46, 'Elantra', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (47, 'Sierra 3500', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (48, 'Tucson', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (49, 'Firebird', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (50, 'Villager', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (51, 'ES', 'Zaam-Dox');
insert into drone (DroneID, Manufacturer, Model) values (52, 'Trans Sport', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (53, 'Escalade', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (54, 'Express 1500', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (55, 'Celica', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (56, 'Thunderbird', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (57, '300ZX', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (58, 'Escalade EXT', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (59, 'VUE', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (60, 'Thunderbird', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (61, 'SL-Class', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (62, 'Lancer Evolution', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (63, 'Yukon XL 2500', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (64, '9-7X', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (65, 'B-Series Plus', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (66, 'GTO', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (67, 'G', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (68, 'Sportvan G20', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (69, 'Corvette', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (70, 'Corvette', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (71, 'Range Rover', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (72, 'Avalon', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (73, 'STS', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (74, 'Mazda6', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (75, 'Enclave', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (76, 'Discovery', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (77, 'Rabbit', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (78, 'Express 1500', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (79, 'IPL G', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (80, 'Econoline E250', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (81, 'Pacifica', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (82, 'Sidekick', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (83, 'S60', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (84, 'XC70', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (85, 'Vantage', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (86, 'Ram Van B350', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (87, '911', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (88, 'Galant', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (89, 'Ram Van B150', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (90, 'Camry', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (91, 'Nubira', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (92, 'XJ Series', 'Treeflex');
insert into drone (DroneID, Manufacturer, Model) values (93, 'Blazer', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (94, 'Camry', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (95, 'F250', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (96, 'Corolla', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (97, 'Defender 90', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (98, '2500', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (99, 'S40', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (100, '330', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (101, 'Envoy XUV', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (102, 'Armada', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (103, 'DeVille', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (104, 'Scoupe', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (105, 'Probe', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (106, 'Sonoma', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (107, 'Impreza', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (108, 'Spirit', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (109, 'Altima', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (110, 'Impala', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (111, 'Lucerne', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (112, 'Discovery', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (113, 'E-Class', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (114, 'QX', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (115, 'XC70', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (116, 'M3', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (117, 'Bronco', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (118, 'Explorer', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (119, '3500 Club Coupe', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (120, 'Elise', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (121, 'Truck', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (122, 'MPV', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (123, 'G-Series G30', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (124, 'Montero Sport', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (125, 'Dakota', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (126, 'Allante', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (127, 'RDX', 'It');
insert into drone (DroneID, Manufacturer, Model) values (128, 'Contour', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (129, '7 Series', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (130, 'Park Avenue', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (131, 'RX-7', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (132, 'S4', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (133, 'XC90', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (134, 'Sephia', 'Zaam-Dox');
insert into drone (DroneID, Manufacturer, Model) values (135, 'Accord Crosstour', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (136, '1500', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (137, 'RAV4', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (138, 'Cayenne', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (139, 'E-Series', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (140, 'Sentra', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (141, 'Sephia', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (142, 'Diablo', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (143, 'Odyssey', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (144, 'Reatta', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (145, 'Loyale', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (146, 'Mark VIII', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (147, 'Villager', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (148, 'XC70', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (149, 'Grand Prix', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (150, 'Sunfire', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (151, 'Celica', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (152, 'Firefly', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (153, 'Town & Country', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (154, 'Liberty', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (155, 'Silverado', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (156, 'Sierra 3500', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (157, 'LeBaron', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (158, 'Century', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (159, 'Jimmy', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (160, 'Quest', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (161, 'Wrangler', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (162, 'Santa Fe', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (163, 'Sonata', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (164, 'Th!nk', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (165, 'Explorer Sport Trac', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (166, 'Passat', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (167, 'XJ Series', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (168, 'I', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (169, 'F250', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (170, 'Murano', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (171, 'Accent', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (172, 'Somerset', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (173, 'Continental', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (174, 'Equator', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (175, 'Z4', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (176, 'Sidekick', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (177, 'Mirage', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (178, 'MX-5', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (179, 'Econoline E350', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (180, 'Caliber', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (181, 'Gallardo', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (182, 'Civic Si', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (183, 'GTI', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (184, 'Grand Marquis', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (185, 'Continental GT', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (186, 'SLK-Class', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (187, 'Coupe', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (188, 'Expedition', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (189, 'XK', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (190, 'Exige', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (191, 'CX-7', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (192, 'Camry', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (193, '8 Series', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (194, 'SJ', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (195, 'Explorer Sport Trac', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (196, 'Mini Cooper', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (197, 'Highlander', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (198, 'Econoline E150', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (199, 'SLK-Class', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (200, 'Sunbird', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (201, 'SC', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (202, 'Grand Prix', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (203, '2500', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (204, 'Taurus', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (205, 'Firebird', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (206, 'Elantra', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (207, '430 Scuderia', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (208, 'CL', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (209, 'Miata MX-5', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (210, 'Miata MX-5', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (211, '626', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (212, 'PT Cruiser', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (213, 'Spectra', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (214, 'B-Series', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (215, 'Aveo', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (216, 'Elan', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (217, 'Discovery', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (218, 'Ram 2500', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (219, 'Loyale', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (220, 'H3', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (221, 'Genesis', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (222, 'S-Series', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (223, 'Quattroporte', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (224, 'V40', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (225, '1 Series', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (226, 'Discovery Series II', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (227, 'Mustang', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (228, 'Chariot', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (229, 'Avalon', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (230, 'Tempest', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (231, 'Highlander', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (232, 'Corolla', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (233, 'Outlook', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (234, 'Truck', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (235, 'Ranger', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (236, 'A6', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (237, 'Town Car', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (238, 'Rainier', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (239, 'Pajero', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (240, 'Stratus', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (241, 'Corvette', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (242, 'Quest', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (243, 'Sable', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (244, 'Sprinter', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (245, 'A8', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (246, 'Trooper', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (247, 'Grand Am', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (248, 'F-Series Super Duty', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (249, 'Justy', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (250, 'Verona', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (251, 'Stratus', 'Zaam-Dox');
insert into drone (DroneID, Manufacturer, Model) values (252, '5 Series', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (253, 'S2000', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (254, 'Mazdaspeed6', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (255, 'A4', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (256, 'Breeze', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (257, 'Ram Van 1500', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (258, 'Chariot', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (259, 'RVR', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (260, 'Safari', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (261, 'Cougar', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (262, 'Mustang', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (263, 'Savana 3500', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (264, 'Veyron', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (265, 'Sierra', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (266, 'Catera', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (267, 'Sunbird', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (268, '5 Series', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (269, 'H1', 'It');
insert into drone (DroneID, Manufacturer, Model) values (270, 'Landaulet', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (271, 'D350 Club', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (272, 'GTI', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (273, 'Mazda3', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (274, 'Explorer Sport Trac', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (275, 'DeVille', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (276, 'Dakota Club', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (277, '80', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (278, 'RAV4', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (279, 'G-Series G30', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (280, '3500 Club Coupe', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (281, 'Spyder', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (282, 'Caliber', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (283, 'Corsica', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (284, 'MDX', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (285, 'STS-V', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (286, 'RL', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (287, 'Explorer', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (288, '7 Series', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (289, 'M-Class', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (290, 'Accord Crosstour', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (291, 'Challenger', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (292, 'Astro', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (293, 'Millenia', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (294, 'Neon', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (295, 'Viper', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (296, 'X5', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (297, '228', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (298, 'Econoline E250', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (299, 'Bonneville', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (300, 'S6', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (301, 'Corsica', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (302, 'S80', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (303, 'Courier', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (304, 'Ram 2500', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (305, 'Bonneville', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (306, 'Malibu', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (307, 'T100', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (308, 'Tracker', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (309, 'Grand Prix', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (310, 'Legend', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (311, 'XG350', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (312, 'MX-5', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (313, '62', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (314, 'Accord', 'Zaam-Dox');
insert into drone (DroneID, Manufacturer, Model) values (315, 'Highlander', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (316, 'Parisienne', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (317, 'Sequoia', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (318, 'Celica', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (319, 'LeMans', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (320, 'Ciera', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (321, 'Ram', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (322, 'RAV4', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (323, 'H1', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (324, 'Continental GT', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (325, 'Boxster', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (326, 'G-Class', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (327, 'Jetta', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (328, 'Escort', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (329, '3500', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (330, 'del Sol', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (331, 'V8 Vantage', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (332, 'LSS', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (333, 'Express 3500', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (334, 'Optima', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (335, '599 GTB Fiorano', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (336, 'S60', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (337, 'riolet', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (338, 'Bonneville', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (339, 'Z4 M', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (340, 'Tahoe', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (341, 'Yukon XL 1500', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (342, 'Spyder', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (343, 'Countryman', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (344, '500', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (345, 'Breeze', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (346, 'Savana 2500', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (347, 'Econoline E350', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (348, 'RX-7', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (349, '57', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (350, 'Intrigue', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (351, 'Aveo', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (352, 'Bonneville', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (353, 'Sebring', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (354, 'Q7', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (355, 'Envoy XL', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (356, 'CL-Class', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (357, 'XC60', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (358, 'SLK-Class', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (359, 'Corrado', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (360, 'VehiCROSS', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (361, 'Forester', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (362, 'Dakota Club', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (363, 'S10', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (364, 'Escape', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (365, 'Z4', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (366, 'A4', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (367, 'S90', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (368, 'SJ', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (369, 'M', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (370, 'Safari', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (371, 'Spirit', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (372, '1500', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (373, 'Continental', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (374, 'Bonneville', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (375, 'Daewoo Lacetti', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (376, 'Mariner', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (377, 'G-Series 1500', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (378, '9-3', 'Treeflex');
insert into drone (DroneID, Manufacturer, Model) values (379, 'Impala', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (380, 'Ion', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (381, 'Accord', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (382, 'Eldorado', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (383, 'SJ', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (384, '3500 Club Coupe', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (385, 'Colorado', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (386, 'MPV', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (387, 'Caliber', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (388, 'M-Class', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (389, 'Econoline E250', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (390, 'ES', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (391, 'Camry', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (392, 'MX-5', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (393, 'FX', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (394, 'S40', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (395, 'Taurus', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (396, 'LaCrosse', 'Treeflex');
insert into drone (DroneID, Manufacturer, Model) values (397, 'Escalade EXT', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (398, 'Sienna', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (399, 'Xterra', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (400, 'Mustang', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (401, 'Mustang', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (402, 'Escalade', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (403, 'Ram 1500', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (404, 'Aztek', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (405, 'Escape', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (406, 'Frontier', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (407, 'S-Class', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (408, 'LR3', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (409, 'Tacoma', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (410, 'Exige', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (411, 'S10', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (412, 'M3', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (413, 'Mazda6', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (414, 'B-Series Plus', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (415, 'Sequoia', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (416, 'Swift', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (417, 'Navajo', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (418, 'Sprinter 2500', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (419, 'Odyssey', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (420, 'Breeze', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (421, 'Tacoma Xtra', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (422, 'Tacoma Xtra', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (423, 'Oasis', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (424, 'Tracker', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (425, 'Range Rover Sport', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (426, 'Vanquish S', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (427, 'Suburban 2500', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (428, '3 Series', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (429, 'Protege5', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (430, 'Sierra', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (431, 'Coupe Quattro', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (432, 'Bonneville', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (433, 'Caprice Classic', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (434, 'G6', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (435, 'Camaro', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (436, 'Cavalier', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (437, 'Eldorado', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (438, 'Venza', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (439, 'Sequoia', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (440, 'QX56', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (441, 'Solara', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (442, 'Thunderbird', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (443, 'Stratus', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (444, 'Bronco II', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (445, 'V40', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (446, 'Insight', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (447, 'S6', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (448, 'CR-V', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (449, 'Phantom', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (450, 'A4', 'It');
insert into drone (DroneID, Manufacturer, Model) values (451, 'Cooper', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (452, 'Breeze', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (453, 'Prizm', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (454, '1500', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (455, 'NX', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (456, 'Bronco', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (457, 'Voyager', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (458, 'Fillmore', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (459, 'Navigator', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (460, 'Ranger', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (461, 'GL-Class', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (462, 'NSX', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (463, 'Sierra 1500', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (464, 'Tiburon', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (465, 'Crown Victoria', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (466, 'Corvette', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (467, 'D150', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (468, 'Ram 3500', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (469, 'Exige', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (470, 'Murano', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (471, 'G35', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (472, 'Jetta', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (473, 'XJ Series', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (474, 'Xterra', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (475, 'Fox', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (476, 'Supra', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (477, 'Camaro', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (478, 'Boxster', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (479, '9-3', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (480, '4Runner', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (481, '2500', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (482, 'IS F', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (483, 'Escort', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (484, 'Metro', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (485, 'Commander', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (486, 'TrailBlazer', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (487, 'S-Class', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (488, 'Cayman', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (489, 'Charger', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (490, '9-5', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (491, 'Esteem', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (492, 'RX-7', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (493, 'Passat', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (494, 'Aerostar', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (495, 'M', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (496, 'Sephia', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (497, 'Eclipse', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (498, 'Land Cruiser', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (499, 'Forenza', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (500, 'CTS', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (501, 'Thunderbird', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (502, 'Elantra', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (503, 'Tiburon', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (504, 'Cavalier', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (505, 'Firebird', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (506, 'Magnum', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (507, 'Mustang', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (508, 'Wrangler', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (509, 'Monaco', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (510, 'Odyssey', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (511, 'Leganza', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (512, 'Corolla', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (513, 'Sequoia', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (514, 'E-Class', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (515, 'Corvette', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (516, 'Passat', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (517, 'Sedona', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (518, 'Express', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (519, 'Safari', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (520, 'Ram Wagon B250', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (521, 'Murciélago', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (522, 'Mustang', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (523, 'Venza', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (524, 'Altima', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (525, 'Pilot', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (526, 'XL-7', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (527, 'Tracker', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (528, 'Phantom', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (529, 'Stylus', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (530, 'Eclipse', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (531, 'S60', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (532, '3 Series', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (533, 'Aerostar', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (534, 'Sequoia', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (535, 'Maxima', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (536, 'Expedition', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (537, 'Justy', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (538, 'MKT', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (539, '740', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (540, 'Suburban 1500', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (541, 'Summit', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (542, 'CTS-V', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (543, '911', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (544, 'E-Series', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (545, '300', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (546, 'Metro', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (547, 'Jimmy', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (548, 'Venture', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (549, 'Sidekick', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (550, 'SVX', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (551, 'SRX', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (552, 'Pathfinder', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (553, 'Versa', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (554, 'Th!nk', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (555, 'Frontier', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (556, 'Highlander Hybrid', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (557, 'Precis', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (558, 'Diamante', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (559, 'X6 M', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (560, 'SC', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (561, 'S-Type', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (562, 'Legacy', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (563, 'Scirocco', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (564, 'Explorer Sport', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (565, 'I', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (566, 'XK', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (567, 'CR-X', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (568, 'Probe', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (569, '911', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (570, 'Suburban 2500', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (571, '370Z', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (572, 'A7', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (573, 'Sentra', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (574, 'SL-Class', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (575, 'Sierra 1500', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (576, 'LeSabre', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (577, 'Grand Cherokee', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (578, 'Intrepid', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (579, 'Q5', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (580, 'Envoy XUV', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (581, 'Magnum', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (582, 'CX-7', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (583, 'Liberty', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (584, 'RL', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (585, 'Avalon', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (586, 'rio', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (587, 'Navigator L', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (588, 'Legacy', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (589, 'Wrangler', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (590, 'Paseo', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (591, 'M3', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (592, 'Tahoe', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (593, 'Equus', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (594, 'Chariot', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (595, 'Tempo', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (596, '5 Series', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (597, 'Legacy', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (598, 'Avalon', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (599, 'LeBaron', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (600, 'LeSabre', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (601, 'Outlook', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (602, 'Mustang', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (603, 'Eclipse', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (604, 'LS', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (605, 'Rocky', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (606, 'Cube', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (607, 'S4', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (608, 'Land Cruiser', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (609, 'FJ Cruiser', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (610, '98', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (611, 'X3', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (612, 'Jetta', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (613, 'Avalanche 1500', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (614, 'Grand Am', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (615, 'Neon', 'It');
insert into drone (DroneID, Manufacturer, Model) values (616, '850', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (617, 'Lumina APV', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (618, '350Z', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (619, 'Diablo', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (620, 'Prelude', 'Zontrax');
insert into drone (DroneID, Manufacturer, Model) values (621, 'Accent', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (622, 'Cabriolet', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (623, 'LS', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (624, 'Taurus', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (625, 'S10', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (626, 'CTS', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (627, 'Savana 2500', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (628, 'Pathfinder', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (629, 'D350', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (630, 'SSR', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (631, 'FX', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (632, 'Continental GTC', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (633, 'GS', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (634, 'Econoline E250', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (635, 'Sonoma Club Coupe', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (636, 'GTI', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (637, 'GTI', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (638, 'Ram 3500', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (639, 'Ranger', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (640, 'Boxster', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (641, 'Tundra', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (642, 'Tahoe', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (643, 'Talon', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (644, 'Yukon XL 1500', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (645, 'Impreza', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (646, 'LX', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (647, 'A8', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (648, 'Amanti', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (649, 'NX', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (650, 'Camaro', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (651, 'SLR McLaren', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (652, 'B-Series', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (653, 'Sonoma', 'Treeflex');
insert into drone (DroneID, Manufacturer, Model) values (654, 'LTD Crown Victoria', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (655, 'Aveo', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (656, 'Safari', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (657, 'GT-R', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (658, 'Xterra', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (659, 'F150', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (660, 'iQ', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (661, 'Dakota', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (662, 'Continental', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (663, 'Insight', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (664, 'Exige', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (665, 'Ram 1500 Club', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (666, 'Cavalier', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (667, 'Magnum', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (668, 'LeSabre', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (669, 'Corvette', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (670, 'Envoy XUV', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (671, 'Cultus', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (672, 'Grand Caravan', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (673, 'Focus', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (674, 'Escalade ESV', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (675, 'Tempo', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (676, 'Eclipse', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (677, 'Carens', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (678, 'Jetta', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (679, '3 Series', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (680, 'Colt', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (681, 'Sentra', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (682, 'Jetta', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (683, 'Mazda6', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (684, 'Legacy', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (685, 'S80', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (686, 'Loyale', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (687, 'Sephia', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (688, 'Quest', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (689, 'RAV4', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (690, 'Frontier', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (691, 'MKX', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (692, 'Caliber', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (693, 'Express 1500', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (694, 'Century', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (695, 'Routan', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (696, 'Thunderbird', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (697, 'Laser', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (698, 'LTD Crown Victoria', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (699, 'Blackwood', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (700, 'Millenia', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (701, 'Explorer', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (702, 'E-Series', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (703, 'Corolla', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (704, 'Jetta', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (705, 'Sierra 1500', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (706, 'Challenger', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (707, 'i-280', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (708, 'C70', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (709, 'Camaro', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (710, 'Aerostar', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (711, 'Intrigue', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (712, 'Altima', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (713, 'Continental', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (714, 'Mustang', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (715, 'Silverado Hybrid', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (716, 'Z4 M', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (717, 'Type 2', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (718, 'SLR McLaren', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (719, 'LS', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (720, 'LS Hybrid', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (721, 'Outlook', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (722, 'Spectra', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (723, 'Mighty Max Macro', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (724, 'Viper', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (725, 'Jetta', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (726, 'Q5', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (727, '3500', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (728, 'EXP', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (729, 'Express 1500', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (730, 'Quattroporte', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (731, 'SJ', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (732, 'F-Series', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (733, 'ES', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (734, 'Spirit', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (735, 'QX56', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (736, 'B9 Tribeca', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (737, 'Integra', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (738, '944', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (739, 'Mini Cooper S', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (740, 'Charger', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (741, 'XL-7', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (742, '6 Series', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (743, '400SE', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (744, 'Cooper', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (745, 'Yaris', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (746, 'RDX', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (747, 'Century', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (748, 'XT', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (749, 'Boxster', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (750, '3 Series', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (751, '4Runner', 'It');
insert into drone (DroneID, Manufacturer, Model) values (752, 'Savana 2500', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (753, '164', 'Regrant');
insert into drone (DroneID, Manufacturer, Model) values (754, 'LX', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (755, 'T100 Xtra', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (756, 'Equator', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (757, 'Sebring', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (758, 'Cherokee', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (759, 'Ram 2500', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (760, 'SSR', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (761, '9-3', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (762, '9-7X', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (763, 'Prius v', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (764, 'RX-7', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (765, 'Cobalt', 'Quo Lux');
insert into drone (DroneID, Manufacturer, Model) values (766, 'Montana', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (767, 'Maxima', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (768, '300', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (769, 'Altima', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (770, 'Jetta III', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (771, 'Jetta', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (772, 'Grand Prix', 'Bitchip');
insert into drone (DroneID, Manufacturer, Model) values (773, 'CX-9', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (774, 'Galant', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (775, 'Millenia', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (776, 'Flex', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (777, '900', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (778, 'Highlander', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (779, 'Wrangler', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (780, 'Galant', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (781, 'Malibu', 'It');
insert into drone (DroneID, Manufacturer, Model) values (782, '323', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (783, 'Voyager', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (784, 'Skylark', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (785, 'G', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (786, 'SL-Class', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (787, 'Z4 M', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (788, 'ES', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (789, 'Golf', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (790, 'Patriot', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (791, 'Spectra', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (792, 'Mazdaspeed6', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (793, 'Mark VIII', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (794, 'Mirage', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (795, '323', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (796, 'Continental Mark VII', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (797, 'Boxster', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (798, 'Windstar', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (799, 'Safari', 'Treeflex');
insert into drone (DroneID, Manufacturer, Model) values (800, 'Millenia', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (801, 'GTO', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (802, 'GTI', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (803, 'GT500', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (804, 'Colt Vista', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (805, 'TundraMax', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (806, 'Riviera', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (807, 'Grand Prix', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (808, 'FJ Cruiser', 'Tres-Zap');
insert into drone (DroneID, Manufacturer, Model) values (809, 'Charger', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (810, 'Camaro', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (811, 'Terraza', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (812, 'E-Series', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (813, 'Ram Van 2500', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (814, 'S10', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (815, 'Skyhawk', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (816, 'Grand Caravan', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (817, '500SL', 'Fix San');
insert into drone (DroneID, Manufacturer, Model) values (818, 'Viper', 'Alphazap');
insert into drone (DroneID, Manufacturer, Model) values (819, '5 Series', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (820, 'CT', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (821, 'Fusion', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (822, 'Yukon XL 2500', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (823, 'Yukon', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (824, 'S2000', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (825, 'Festiva', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (826, 'Stratus', 'Keylex');
insert into drone (DroneID, Manufacturer, Model) values (827, 'Concorde', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (828, 'Durango', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (829, 'A8', 'Y-Solowarm');
insert into drone (DroneID, Manufacturer, Model) values (830, 'Neon', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (831, 'Vision', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (832, 'Jetta', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (833, 'Golf', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (834, 'Bravada', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (835, 'SLK-Class', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (836, 'Sonata', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (837, 'Vitara', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (838, 'Impreza WRX', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (839, 'Mountaineer', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (840, 'Tahoe', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (841, 'Monterey', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (842, 'Safari', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (843, 'E-Class', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (844, 'Ram 2500', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (845, 'GTI', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (846, 'Sentra', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (847, 'Stratus', 'Veribet');
insert into drone (DroneID, Manufacturer, Model) values (848, 'Flex', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (849, 'Legend', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (850, 'Ram Van 2500', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (851, 'Bonneville', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (852, 'Veracruz', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (853, 'Galant', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (854, 'Cabriolet', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (855, 'T100', 'Konklab');
insert into drone (DroneID, Manufacturer, Model) values (856, 'Riviera', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (857, 'Quattroporte', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (858, 'Astro', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (859, 'Aviator', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (860, 'Boxster', 'Cookley');
insert into drone (DroneID, Manufacturer, Model) values (861, 'Reatta', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (862, 'Grand Marquis', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (863, 'Passat', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (864, 'Xterra', 'Lotlux');
insert into drone (DroneID, Manufacturer, Model) values (865, 'Neon', 'It');
insert into drone (DroneID, Manufacturer, Model) values (866, 'C70', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (867, 'Chariot', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (868, 'GTI', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (869, 'D250', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (870, 'Savana', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (871, 'Premier', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (872, 'Diablo', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (873, 'Echo', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (874, 'Mystique', 'Toughjoyfax');
insert into drone (DroneID, Manufacturer, Model) values (875, 'Mountaineer', 'Flexidy');
insert into drone (DroneID, Manufacturer, Model) values (876, 'Sunfire', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (877, 'Savana 1500', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (878, 'Ram Van B350', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (879, 'Genesis', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (880, 'Ram 3500', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (881, 'A4', 'Andalax');
insert into drone (DroneID, Manufacturer, Model) values (882, 'CTS', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (883, 'Accord', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (884, 'Yukon XL 2500', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (885, 'Passat', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (886, 'G37', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (887, 'S4', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (888, 'Continental', 'Zoolab');
insert into drone (DroneID, Manufacturer, Model) values (889, 'Econoline E250', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (890, 'Vandura 3500', 'Temp');
insert into drone (DroneID, Manufacturer, Model) values (891, 'Caliber', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (892, 'Wrangler', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (893, 'RL', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (894, '745', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (895, 'Camry', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (896, 'Camry Hybrid', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (897, '525', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (898, 'Civic', 'Fintone');
insert into drone (DroneID, Manufacturer, Model) values (899, 'Swift', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (900, '458 Italia', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (901, 'Legend', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (902, 'Camaro', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (903, 'Express 2500', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (904, 'Quattroporte', 'Cardify');
insert into drone (DroneID, Manufacturer, Model) values (905, 'Escalade ESV', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (906, 'Skyhawk', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (907, '7 Series', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (908, 'X6', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (909, 'Liberty', 'Bigtax');
insert into drone (DroneID, Manufacturer, Model) values (910, 'Explorer', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (911, 'XL-7', 'Vagram');
insert into drone (DroneID, Manufacturer, Model) values (912, 'X5', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (913, 'Roadmaster', 'Latlux');
insert into drone (DroneID, Manufacturer, Model) values (914, 'SC', 'Lotstring');
insert into drone (DroneID, Manufacturer, Model) values (915, 'Passport', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (916, 'Diablo', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (917, 'Milan', 'Bitwolf');
insert into drone (DroneID, Manufacturer, Model) values (918, 'Swift', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (919, 'Elantra', 'Transcof');
insert into drone (DroneID, Manufacturer, Model) values (920, 'Skyhawk', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (921, 'Lancer Evolution', 'Daltfresh');
insert into drone (DroneID, Manufacturer, Model) values (922, 'Lancer', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (923, 'Jimmy', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (924, '850', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (925, 'Explorer Sport', 'Hatity');
insert into drone (DroneID, Manufacturer, Model) values (926, 'X5', 'Opela');
insert into drone (DroneID, Manufacturer, Model) values (927, 'Supra', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (928, 'Suburban 1500', 'Tresom');
insert into drone (DroneID, Manufacturer, Model) values (929, 'Compass', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (930, 'QX', 'Zathin');
insert into drone (DroneID, Manufacturer, Model) values (931, 'CL-Class', 'Bamity');
insert into drone (DroneID, Manufacturer, Model) values (932, 'Dakota', 'Biodex');
insert into drone (DroneID, Manufacturer, Model) values (933, 'EXP', 'Holdlamis');
insert into drone (DroneID, Manufacturer, Model) values (934, 'Monte Carlo', 'Ronstring');
insert into drone (DroneID, Manufacturer, Model) values (935, 'S10', 'Flowdesk');
insert into drone (DroneID, Manufacturer, Model) values (936, 'Tucson', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (937, 'Fleetwood', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (938, 'LX', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (939, 'New Beetle', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (940, 'Express', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (941, 'Allante', 'Namfix');
insert into drone (DroneID, Manufacturer, Model) values (942, 'Range Rover', 'Tempsoft');
insert into drone (DroneID, Manufacturer, Model) values (943, 'Outlook', 'Asoka');
insert into drone (DroneID, Manufacturer, Model) values (944, 'Amigo', 'Trippledex');
insert into drone (DroneID, Manufacturer, Model) values (945, 'Prizm', 'Matsoft');
insert into drone (DroneID, Manufacturer, Model) values (946, 'TL', 'Sonair');
insert into drone (DroneID, Manufacturer, Model) values (947, 'i-290', 'Solarbreeze');
insert into drone (DroneID, Manufacturer, Model) values (948, 'Tiburon', 'It');
insert into drone (DroneID, Manufacturer, Model) values (949, 'Regal', 'Zamit');
insert into drone (DroneID, Manufacturer, Model) values (950, 'Samurai', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (951, 'Truck', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (952, 'New Beetle', 'Stim');
insert into drone (DroneID, Manufacturer, Model) values (953, 'Sequoia', 'Alpha');
insert into drone (DroneID, Manufacturer, Model) values (954, 'Cayenne', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (955, 'Sierra', 'Rank');
insert into drone (DroneID, Manufacturer, Model) values (956, 'RVR', 'Y-find');
insert into drone (DroneID, Manufacturer, Model) values (957, 'Suburban 2500', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (958, 'Pajero', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (959, 'Mariner', 'Otcom');
insert into drone (DroneID, Manufacturer, Model) values (960, 'Explorer Sport Trac', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (961, 'Xterra', 'Sonsing');
insert into drone (DroneID, Manufacturer, Model) values (962, 'CR-V', 'Home Ing');
insert into drone (DroneID, Manufacturer, Model) values (963, 'Mariner', 'Bytecard');
insert into drone (DroneID, Manufacturer, Model) values (964, 'Flex', 'Domainer');
insert into drone (DroneID, Manufacturer, Model) values (965, 'SX4', 'Sub-Ex');
insert into drone (DroneID, Manufacturer, Model) values (966, 'Jetta', 'Viva');
insert into drone (DroneID, Manufacturer, Model) values (967, 'F350', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (968, 'Mazda2', 'Gembucket');
insert into drone (DroneID, Manufacturer, Model) values (969, 'DB9', 'Stronghold');
insert into drone (DroneID, Manufacturer, Model) values (970, 'Venza', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (971, 'Navigator', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (972, 'Dakota Club', 'Prodder');
insert into drone (DroneID, Manufacturer, Model) values (973, 'Esprit', 'Tampflex');
insert into drone (DroneID, Manufacturer, Model) values (974, 'Colorado', 'Mat Lam Tam');
insert into drone (DroneID, Manufacturer, Model) values (975, 'Sentra', 'Wrapsafe');
insert into drone (DroneID, Manufacturer, Model) values (976, 'Eclipse', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (977, 'Civic', 'Stringtough');
insert into drone (DroneID, Manufacturer, Model) values (978, 'LaCrosse', 'Voltsillam');
insert into drone (DroneID, Manufacturer, Model) values (979, '911', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (980, 'V70', 'Zaam-Dox');
insert into drone (DroneID, Manufacturer, Model) values (981, 'VS Commodore', 'Voyatouch');
insert into drone (DroneID, Manufacturer, Model) values (982, 'M3', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (983, 'Impala', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (984, 'Magnum', 'Tin');
insert into drone (DroneID, Manufacturer, Model) values (985, 'Pajero', 'Span');
insert into drone (DroneID, Manufacturer, Model) values (986, 'Tracer', 'Kanlam');
insert into drone (DroneID, Manufacturer, Model) values (987, 'Land Cruiser', 'Overhold');
insert into drone (DroneID, Manufacturer, Model) values (988, 'CX-9', 'Redhold');
insert into drone (DroneID, Manufacturer, Model) values (989, 'Yaris', 'Ventosanzap');
insert into drone (DroneID, Manufacturer, Model) values (990, 'Titan', 'Greenlam');
insert into drone (DroneID, Manufacturer, Model) values (991, 'Aviator', 'Aerified');
insert into drone (DroneID, Manufacturer, Model) values (992, '525', 'Fixflex');
insert into drone (DroneID, Manufacturer, Model) values (993, 'SLK-Class', 'Job');
insert into drone (DroneID, Manufacturer, Model) values (994, 'XJ', 'Cardguard');
insert into drone (DroneID, Manufacturer, Model) values (995, 'Escort', 'Konklux');
insert into drone (DroneID, Manufacturer, Model) values (996, 'New Beetle', 'Subin');
insert into drone (DroneID, Manufacturer, Model) values (997, 'Quest', 'Pannier');
insert into drone (DroneID, Manufacturer, Model) values (998, 'Seville', 'It');
insert into drone (DroneID, Manufacturer, Model) values (999, 'Integra', 'Duobam');
insert into drone (DroneID, Manufacturer, Model) values (1000, 'Jetta', 'Y-Solowarm');
